services:
  perplexica-mcp:
    build: .
    image: perplexica-mcp-sse
    container_name: perplexica-mcp-sse
    ports:
      - "3001:3001"
    env_file:
      - .env
    command: python src/perplexica_mcp/server.py sse  # SSE transport
    restart: unless-stopped
    networks:
      - perplexica-network
    healthcheck:
      test: [
        "CMD", 
        "python", 
        "-c", 
        "import urllib.request; req = urllib.request.Request('http://localhost:3001/sse'); req.add_header('Accept', 'text/event-stream'); urllib.request.urlopen(req, timeout=5)"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  perplexica-network:
    external: true
