services:
  perplexica-mcp:
    build: .
    image: perplexica-mcp-http
    container_name: perplexica-mcp-http
    ports:
      - "3001:3001"
    env_file:
      - .env
    command: python src/perplexica_mcp/server.py http  # Streamable HTTP transport
    restart: unless-stopped
    networks:
      - perplexica-network
    healthcheck:
      test: [
        "CMD", 
        "python", 
        "-c", 
        "import urllib.request, json; req = urllib.request.Request('http://localhost:3001/mcp', data=json.dumps({'jsonrpc': '2.0', 'method': 'initialize', 'params': {'protocolVersion': '2024-11-05', 'capabilities': {}, 'clientInfo': {'name': 'healthcheck', 'version': '1.0.0'}}, 'id': 1}).encode(), headers={'Content-Type': 'application/json', 'Accept': 'application/json, text/event-stream'}); urllib.request.urlopen(req)"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  perplexica-network:
    external: true
